"""Render the Discovery graph to docs/, so the diagram tracks the code.

    uv run python scripts/draw_graph.py

Writes a Mermaid source file, a Markdown page that renders on GitHub, and a PNG
when mermaid.ink is reachable. No database, no API keys, no cost.
"""

from __future__ import annotations

import sys
from pathlib import Path

from opportunity_radar.discovery.budget import RunBudget
from opportunity_radar.discovery.state import WorkflowRuntime
from opportunity_radar.discovery.workflow import build_discovery_graph

DOCS = Path(__file__).resolve().parents[1] / "docs"


def main() -> int:
    runtime = WorkflowRuntime(
        db=None, budget=RunBudget(), model="(diagram)", dry_run=True,
        run_id="diagram",
    )
    graph = build_discovery_graph(runtime).get_graph()
    DOCS.mkdir(exist_ok=True)

    mermaid = graph.draw_mermaid()
    (DOCS / "graph.mmd").write_text(mermaid, encoding="utf-8")
    (DOCS / "graph.md").write_text(
        "# Discovery pipeline\n\n"
        "Generated by `scripts/draw_graph.py` — regenerate after changing the "
        "graph.\n\n"
        "| Step | Job | Reaches out to |\n"
        "|---|---|---|\n"
        "| `plan` | write the search queries | model |\n"
        "| `search` | run the queries not yet run, in two waves | Tavily |\n"
        "| `rank` | order the pool best-first, choose sites and say why | model, Mongo |\n"
        "| `fetch` | get the pages for **one** site | Firecrawl, model |\n"
        "| `extract` | read **one** site, build and check its records | model |\n"
        "| `evaluate` | judge each record against the profile | model |\n"
        "| `store` | write each record once, with its verdict | Mongo |\n\n"
        "`fetch` and `extract` run once per site, in parallel. `evaluate` is the "
        "single fan-in, which is why the re-plan decision lives there.\n\n"
        f"```mermaid\n{mermaid}```\n",
        encoding="utf-8",
    )
    print(f"wrote {DOCS / 'graph.mmd'}")
    print(f"wrote {DOCS / 'graph.md'}")

    try:
        png = graph.draw_mermaid_png()
    except Exception as exc:  # noqa: BLE001 — the text versions are the point
        print(f"PNG skipped ({type(exc).__name__}); the .md renders anywhere")
        return 0
    (DOCS / "graph.png").write_bytes(png)
    print(f"wrote {DOCS / 'graph.png'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
